### ISSUE TITLE
Build is broken on recent parrot.

### ISSUE THREAD

**Issue by coke** [partcl/partcl#2]
If you try to build on a recent parrot, you get a memory corruption error:

$ make                                     /home/coke/bird/bin/parrot --output=runtime/tcllib.pbc runtime/tcllib.pir
**\* glibc detected **\* /home/coke/bird/bin/parrot: malloc(): memory corruption: 0x09ca9270 ***
======= Backtrace: =========

If you run this without the --output, you get:

$ /home/coke/bird/bin/parrot runtime/tcllib.pir
Null PMC access in type()
current instr.: 'mappings' pc 28 (runtime/tcllib.pir:49)

**Comment by leto** [comment]
Can you bisect this issue? Here is an example bisection script: https://github.com/leto/Util/blob/master/bin/parrot-bisect.sh Let me know if you need more help with git bisect.

**Comment by coke** [comment]
On Mon, Oct 31, 2011 at 11:35 PM, Jonathan Duke Leto
reply@reply.github.com
wrote:

> Can you bisect this issue? Here is an example bisection script: https://github.com/leto/Util/blob/master/bin/parrot-bisect.sh Let me know if you need more help with git bisect.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/partcl/partcl/issues/2#issuecomment-2586423

Unable to duplicate the error on OS X, btw - only occurs on linux
(feather.perl6.nl), where I first noticed it.

Here's the result of the bisect:

d6a0c0f5db4a1ce8c4a0fec9681d418afae34437 is the first bad commit
commit d6a0c0f5db4a1ce8c4a0fec9681d418afae34437
Author: Whiteknight wknight8111@gmail.com
Date:   Thu Sep 29 11:37:44 2011 -0400

```
Simplify argument passing to :main. Always pass exactly one PMC
```

arg to :main. The new frontend combines it's two arrays into a single
array argument, and parses that out.

## 

Will "Coke" Coleda

**Comment by Benabik** [comment]
I was unable to replicate the memory corruption, but at least I got it to build.  (See pull request, above.)

**Comment by coke** [comment]
Applied, thanks - I wasn't even getting to the build failure. (and still am not, the memory corruption is still occuring.)

**Comment by coke** [comment]
This was being tracked in parrot at 

https://github.com/parrot/parrot/issues/185

**Comment by coke** [comment]
The build works again.
